format = '''
${custom.host}$directory$python$git_branch$git_state$time
> 
'''

[custom.host]
command = '[ -n "$CODER_WORKSPACE_NAME" ] && echo "$CODER_WORKSPACE_NAME" || hostname -s'
when = "true"
format = '[($output):]($style)'
style = 'green'

[hostname]
format = '[($hostname:)]($style)'
ssh_only = false
style = 'green'
aliases = {"StevenMBP" = "MBP", "Range-Laptop" = "MBP"}

[directory]
truncate_to_repo = true
fish_style_pwd_dir_length = 1
style = 'white'
repo_root_style = 'bold yellow'
home_symbol = '~/steven'

[git_branch]
format = '[($branch)](cyan bold)[( => $remote_name/$remote_branch)](cyan) '

[git_state]
style = 'yellow'

[time]
disabled = false
time_format = '%F %T %Z'
style = 'green'

[python]
detect_extensions = []
pyenv_version_name = true
